# Generated by Django 5.2.13 on 2026-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tshirts", "T-Shirts"),
                            ("shirts", "Shirts"),
                            ("jeans", "Jeans"),
                            ("jackets", "Jackets"),
                        ],
                        default="tshirts",
                        max_length=20,
                    ),
                ),
                ("price", models.PositiveIntegerField(help_text="Price in NPR")),
                (
                    "old_price",
                    models.PositiveIntegerField(
                        blank=True, help_text="Old price in NPR", null=True
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("new", "New"),
                            ("trending", "Trending"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="👕",
                        help_text="Emoji/icon for placeholder UI",
                        max_length=10,
                    ),
                ),
                (
                    "bg",
                    models.CharField(
                        default="p-bg-1",
                        help_text="Background class for card placeholder",
                        max_length=20,
                    ),
                ),
                ("emoji", models.CharField(default="🖤", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
