# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.CharField(default="Black,White,Navy", help_text="Comma-separated colors", max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(default="XS,S,M,L,XL,XXL", help_text="Comma-separated sizes", max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_status",
            field=models.CharField(default="In stock", max_length=80),
        ),
    ]
