# Generated by Django 5.1.5 on 2026-05-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_colors_product_sizes_product_stock_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default="THE BOLD\nCOLLECTION")),
                (
                    "season",
                    models.CharField(default="Summer Season 2025", max_length=120),
                ),
                ("season_code", models.CharField(default="SS 2025", max_length=40)),
                (
                    "description",
                    models.TextField(
                        default="Crafted for those who don't follow trends - they set them. The Krishna SS25 collection blends streetwear edge with everyday comfort."
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        default="Premium breathable fabric\nLimited edition colorways\nSizes XS to XXL available\nAffordable luxury pricing",
                        help_text="Write one feature per line.",
                    ),
                ),
                ("badge", models.CharField(default="EXCLUSIVE DROP", max_length=80)),
                ("visual_number", models.CharField(default="25", max_length=20)),
                (
                    "icon",
                    models.CharField(
                        default="F",
                        help_text="Short icon or emoji for the visual card",
                        max_length=10,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(default="SHOP THE DROP", max_length=80),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leave blank to open the shop page",
                        max_length=200,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="drops/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
